language: java
jdk:
  - oraclejdk8
sudo: false

script: "mvn cobertura:cobertura"

notifications:
  webhooks:
    urls:
      - http://lowcost-env.x8pcftmhaw.us-east-1.elasticbeanstalk.com/

after_success:
  - bash <(curl -s https://codecov.io/bash)