language: java
jdk:
  - oraclejdk8
sudo: false

script: "mvn cobertura:cobertura"

notifications:
  webhooks:
    urls:
      - https://l1x8ie75li.execute-api.us-east-1.amazonaws.com/test/travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)